### PR TITLE
Fix applicability logic for EUSS economizer fault measures

### PR DESCRIPTION
**Pull request by JanghyunJK**
Pull request overview
---------------------
- there was a mistake in the previous economizer fault implementation (details of implementation are described in the [change doc](https://nrel.sharepoint.com/:w:/r/sites/comstock/Shared%20Documents/ComStock%20Filing%20Cabinet/Change%20Documentation/Changes/v17%20Economizers/ComStock%20Economizers.docx?d=w4b976b2895474545a57347ce41bb5e28&csf=1&web=1&e=pE2K1R))

- [new change documentation](https://nrel.sharepoint.com/:w:/r/sites/comstock/Shared%20Documents/ComStock%20Filing%20Cabinet/ComStock%20Core/Change%20Documentation/Changes/vTBD%20Economizer/ComStock%20Economizers.docx?d=w99ef0eda8767474db858dd4a2f54ab99&csf=1&web=1&e=krKelC) prepared

- mistake = we were skipping economizers that are in unitary systems (e.g., PSZs)

- so this is including unitary system back to applicability and adding unit tests with example models

- cc-ing: @ChristopherCaradonna @asparke2 

### Pull Request Author: JK

Type of pull request (select all the apply):
 - [ ] Sampling
 - [X] Core model measure
 - [ ] End-Use Savings Shapes measure
 - [ ] Reporting measure
 - [ ] Singularity image / Buildstock batch
 - [ ] Postprocessing
 - [ ] Documentation

 - [X] Added tests for new measures
 - [X] Updated measure .xml(s)
 - [ ] Register values added to `comstock_column_definitions.csv`
 - [ ] Both `options_lookup.tsv` files updated
 - [x] 10k+ test run
 - [x] Change documentation written
 - [ ] Measure documentation written
 - [ ] Comstock documentation updated
 - [ ] Changes reflected in example `.yml` files
 - [ ] Changes reflected in `README.md` files
 - [ ] Added 'See ComStock License' language to first two lines of each code file
 - [ ] All new and existing tests pass the CI

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a code review on GitHub
 - [ ] All related changes have been implemented: data and method additions, changes, tests
 - [ ] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] Reviewed change documentation
 - [ ] Ensured code files contain License reference
 - [ ] Results differences are reasonable
 - [ ] CI status: all tests pass

### CODE REVIEW

**Comment by JanghyunJK** [comment]
TODO:

- do 10k test
- create change doc

**Comment by JanghyunJK** [comment]
@ChristopherCaradonna 10k test done and [new change doc](https://nrel.sharepoint.com/:w:/r/sites/comstock/Shared%20Documents/ComStock%20Filing%20Cabinet/ComStock%20Core/Change%20Documentation/Changes/vTBD%20Economizer/ComStock%20Economizers.docx?d=w99ef0eda8767474db858dd4a2f54ab99&csf=1&web=1&e=krKelC) added.

**Review by ChristopherCaradonna — CHANGES_REQUESTED** [review]
Add stacked end use bar plot and gas/electricity plots by building type to change document (these are automatically generated in postprocessing). Otherwise this looks good to merge.

**Comment by JanghyunJK** [comment]
@ChristopherCaradonna measure updated with additional plots!

**Comment by JanghyunJK** [comment]
@ChristopherCaradonna I want to merge this before 10k for economizer measure!

**Review by ChristopherCaradonna — APPROVED** [review]

**Pull request merged**
