### PR TITLE
openstudio-standards update

### LINKED ISSUE #60: ChangeBuildingLocation assigns full climate zone document designations to OS:ClimateZones 'Value' field
Current options for ASHRAE 'climate_zone' arguments in ChangeBuildingLocation measure specify ASHRAE 169-2013: 
https://github.com/NREL/ComStock/blob/a541f15d27206f4e23d56be53ef8b7e154edda9e/resources/measures/ChangeBuildingLocation/measure.rb#L102-L118

But when the measure sets the climate zone info in the model, it tries to remove the string 'ASHRAE 169-2006-' from the climate zone argument: https://github.com/NREL/ComStock/blob/a541f15d27206f4e23d56be53ef8b7e154edda9e/resources/measures/ChangeBuildingLocation/measure.rb#L357

This results in the 'value' field of the OS:ClimateZones object populated with the whole climate zone string: 
image

where it should just be the designation: 
https://github.com/NREL/OpenStudio/blob/05c60768c1e1057083ce644d49711f7377f8ce1e/src/model/ClimateZones.hpp#L42-L44

I think the only implication of the value field containing the whole cz string is that any measure that uses the value has to strip out the extra characters, as in 'set nist infiltration coefficients': https://github.com/NREL/ComStock/blob/a541f15d27206f4e23d56be53ef8b7e154edda9e/resources/measures/set_nist_infiltration_correlations/measure.rb#L524-L528

But check if there's anything in postprocessing that might be affected by this.

### PR DESCRIPTION
**Pull request by mdahlhausen**
Pull request overview
---------------------
This PR updates ComStock to use the latest version of openstudio-standards (0.6.2 interm release)

 - Fixes #60 and #172 

### Pull Request Author

This pull request makes changes to (select all the apply):
 - [ ] Documentation
 - [x] Infrastructure (includes apptainer image, buildstock batch, dependencies, continuous integration tests)
 - [ ] Sampling
 - [x] Workflow Measures
 - [x] Upgrade Measures
 - [x] Reporting Measures
 - [ ] Postprocessing

Author pull request checklist:
 - [x] Tagged the pull request with the appropriate label (documentation, infrastructure, sampling, workflow measure, upgrade measure, reporting measure, postprocessing) to help categorize changes in the release notes.
 - [x] Added tests for new measures
 - [x] Updated measure .xml(s)
 - [x] 10k+ test run
 - [x] Change documentation written
 - [x] ComStock documentation updated
 - [x] Changes reflected in example `.yml` files
 - [x] Changes reflected in `README.md` files
 - [x] Added 'See ComStock License' language to first two lines of each code file
 - [ ] All new and existing tests pass the CI

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [x] Perform a code review on GitHub
 - [x] All related changes have been implemented: data and method additions, changes, tests
 - [x] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [x] Reviewed change documentation
 - [x] Ensured code files contain License reference
 - [x] Results differences are reasonable
 - [x] Make sure the newly added measures has been added with tests and indexed properly
 - [x] CI status: all tests pass

#### ComStock Licensing Language - Add to Beginning of Each Code File
```
# ComStock™, Copyright (c) 2023 Alliance for Sustainable Energy, LLC. All rights reserved.
# See top level LICENSE.txt file for license terms.
```

### CODE REVIEW

**Review by eringold — COMMENTED** [review]
These changes look good. Do you intend to update/refactor ChangeBuildingLocation in a separate PR?

**Comment by mdahlhausen** [comment]
> These changes look good. Do you intend to update/refactor ChangeBuildingLocation in a separate PR?

Yes, in a separate PR. The buildstock weather .stat files miss a lot of the information necessary for the weather methods in standards. I'll need to make some smart defaults or adjustments, and alternative calculation pathways to determine things like design day criteria.

**Comment by bonnema** [comment]
> > These changes look good. Do you intend to update/refactor ChangeBuildingLocation in a separate PR?
> 
> Yes, in a separate PR. The buildstock weather .stat files miss a lot of the information necessary for the weather methods in standards. I'll need to make some smart defaults or adjustments, and alternative calculation pathways to determine things like design day criteria.

@carlobianchi89 may have some insight here

**Comment by mdahlhausen** [comment]
> > > These changes look good. Do you intend to update/refactor ChangeBuildingLocation in a separate PR?
> > 
> > 
> > Yes, in a separate PR. The buildstock weather .stat files miss a lot of the information necessary for the weather methods in standards. I'll need to make some smart defaults or adjustments, and alternative calculation pathways to determine things like design day criteria.
> 
> @carlobianchi89 may have some insight here

We could regenerate the ComStock data files to include more information in the .stat file. But since many of the fields are calculated from the .epw, it may make sense to just have a method to calculate them. Things like design days, degree days, and ground temperatures.

I do know there needs to be more error checking on the weather files anyways. So perhaps an opportunity to add content to the .stat files too. Dru Crawley and One Building have code to calculate that information.

**Review by eringold — DISMISSED** [review]

**Review by ChristopherCaradonna — APPROVED** [review]

**Pull request merged**
